# Generated by Django 5.0.4 on 2024-04-25 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='protocole',
            new_name='protocolo',
        ),
    ]
